{
 "title": "AWS CloudWatch Metrics",
 "time": { "from": "2025-01-08T13:33:05.889Z", "to": "2025-01-08T20:31:34.069Z" },
 "panels": [
  {
   "title": "EC2 Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-03ce6a092fb62d08e" },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "InstanceId": "i-03ce6a092fb62d08e" },
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "EC2 System Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-03ce6a092fb62d08e" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "i-03ce6a092fb62d08e" },
     "metricName": "DiskReadOps",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "i-03ce6a092fb62d08e" },
     "metricName": "DiskWriteOps",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ETL Lambda Metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expression": "FILL(invocs, 0)",
     "id": "invokef",
     "label": "Total Invocations",
     "metricEditorMode": 1,
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expression": "FILL(errors, 0)",
     "id": "errorf",
     "label": "Total Errors",
     "metricEditorMode": 1,
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expression": "FILL(avgtime, 0)",
     "id": "timef",
     "label": "Average duration",
     "metricEditorMode": 1,
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Load Lambda Metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expression": "FILL(invocs, 0)",
     "id": "invokef",
     "label": "Total Invocations",
     "metricEditorMode": 1,
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expression": "FILL(errors, 0)",
     "id": "errorf",
     "label": "Total Errors",
     "metricEditorMode": 1,
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expression": "FILL(avgtime, 0)",
     "id": "timef",
     "label": "Average duration",
     "metricEditorMode": 1,
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}