{
 "title": "Trends",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Revenue By Date ",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    DATE(transaction.timestamp) AS \"Date\",\r\n    SUM(transaction.total_price) AS \"Total Revenue\"\r\nFROM \r\n    transaction\r\nGROUP BY \r\n    DATE(transaction.timestamp)\r\nORDER BY \r\n    \"Date\" ASC;\r\n"
    }
   ]
  },
  {
   "title": "Total Item Quantity Sold Per Branch (All time)",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    branch.name AS \"Branch\",\r\n    SUM(transaction_item.quantity) AS \"Total Item Quantity\"\r\nFROM \r\n    transaction\r\nJOIN \r\n    transaction_item ON transaction.id = transaction_item.transaction_id\r\nJOIN \r\n    branch ON transaction.branch_id = branch.id\r\nGROUP BY \r\n    branch.name\r\nORDER BY \r\n    \"Total Item Quantity\" DESC;\r\n"
    }
   ]
  },
  {
   "title": "Total Revenue Per Branch Daily (£)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    branch.name AS \"Branch\",\r\n    DATE(transaction.timestamp) AS \"Date\",\r\n    SUM(transaction.total_price) AS \"Daily Revenue\"\r\nFROM \r\n    transaction\r\nJOIN \r\n    branch ON transaction.branch_id = branch.id\r\nGROUP BY \r\n    branch.name, DATE(transaction.timestamp)\r\nORDER BY \r\n    \"Date\" ASC, \"Branch\";\r\n"
    }
   ]
  },
  {
   "title": "Top Sold Item By Branch ",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    b.name AS branch_name, \r\n    i.name AS item_name, \r\n    i.size AS item_size, \r\n    v.name AS variant_name, \r\n    SUM(ti.quantity) AS total_quantity_sold\r\nFROM \r\n    transaction t\r\nJOIN \r\n    transaction_item ti ON t.id = ti.transaction_id\r\nJOIN \r\n    item i ON ti.item_id = i.id\r\nJOIN \r\n    variant v ON ti.variant_id = v.id  -- Added join for variant\r\nJOIN \r\n    branch b ON t.branch_id = b.id\r\nGROUP BY \r\n    b.name, i.name, i.size, v.name\r\nORDER BY \r\n    total_quantity_sold DESC;\r\n"
    }
   ]
  }
 ]
}